import type { ImageSourcePropType } from 'react-native';

export const gameArtwork: Record<string, ImageSourcePropType> = {
  wavelength: require('../../assets/game-cards/opa-wavelength-tt-v1.jpg'),
  wordrush: require('../../assets/game-cards/opa-wordrush-tt-v1.jpg'),
  rulecard: require('../../assets/game-cards/opa-rulecard-tt-v1.jpg'),
  darecard: require('../../assets/game-cards/opa-darecard-tt-v1.jpg'),
  mostlikely: require('../../assets/game-cards/opa-mostlikely-tt-v1.jpg'),
  herd: require('../../assets/game-cards/opa-herd-tt-v1.jpg'),
  standards: require('../../assets/game-cards/opa-standards-tt-v1.jpg'),
  tenbut: require('../../assets/game-cards/opa-tenbut-tt-v1.jpg'),
  impostor: require('../../assets/game-cards/opa-impostor-tt-v1.jpg'),
  spy: require('../../assets/game-cards/opa-spy-tt-v1.jpg'),
  charades: require('../../assets/game-cards/opa-charades-tt-v2.jpg'),
  bomb: require('../../assets/game-cards/opa-bomb-tt-v1.jpg'),
  mafia: require('../../assets/game-cards/opa-mafia-tt-v1.jpg'),
  whowrote: require('../../assets/game-cards/opa-whowrote-tt-v1.jpg'),
  twotruths: require('../../assets/game-cards/opa-twotruths-tt-v2.jpg'),
  never: require('../../assets/game-cards/opa-never-tt-v1.jpg'),
  nolaugh: require('../../assets/game-cards/opa-nolaugh-tt-v1.jpg'),
  noyesno: require('../../assets/game-cards/opa-noyesno-tt-v1.jpg'),
  alias: require('../../assets/game-cards/opa-alias-tt-v2.jpg'),
  truthdare: require('../../assets/game-cards/opa-truthdare-tt-v1.jpg'),
  whoami: require('../../assets/game-cards/opa-whoami-tt-v2.jpg'),
  // მინი-თამაშები — საკუთარ ყდამდე House Rules-ის ყდა.
};

export const gameCaptions: Record<string, string> = {
  "noyesno": "უპასუხე ისე, რომ „კი“ ან „არა“ არ თქვა.",
  "mostlikely": "ვის შეეფერება ეს აღწერა?",
  "herd": "უპასუხე ისე, როგორც უმრავლესობა.",
  "standards": "ნორმაა თუ გადამეტებაა? იმსჯელეთ ერთად.",
  "tenbut": "გამოიცანი მეგობრის შეფასება.",
  "impostor": "გამოიცანი, ვინ ბლეფობს.",
  "spy": "იპოვე, ვის აქვს სხვა სიტყვა.",
  "charades": "შუბლზე დაიდე და გამოიცანი.",
  "bomb": "თქვი სიტყვა და გადაეცი ტელეფონი.",
  "mafia": "გამოიცანი, ვინ არის მაფია.",
  "whowrote": "გამოიცანი, ვინ დაწერა პასუხი.",
  "twotruths": "სამი ამბიდან რომელია ტყუილი?",
  "never": "აღიარე, თუ შენც გაგიკეთებია.",
  "nolaugh": "ეცადე, არ გაგეცინოს.",
  "alias": "აუხსენი სიტყვა შენს გუნდს.",
  "truthdare": "სიმართლე თუ მოქმედება?",
  "whoami": "კითხვებით გამოიცანი, ვინ ხარ.",
  "wavelength": "გამოიცანით ადგილი შკალაზე.",
  "wordrush": "რამდენ სიტყვას მოასწრებ?",
  "rulecard": "დაიმახსოვრე და დაიცავი წესები.",
  "darecard": "შეასრულე დავალება ან მიიღე ჯარიმა."
};
